version: '3.8'
services:
  manager:
    image: dadyarri/9f840c17c6fd49dfb786607fdfb89e85:latest-staging
    container_name: choco_main
    ports:
      - "443:443"
      - "80:80"
    environment:
      ASPNETCORE_HTTPS_POST: 443
    volumes:
      - "./static:/usr/share/fonts"
      - "./.env:/app/.env"
      - "./certs:/etc/certs"
    depends_on:
      - managerDb
    networks:
      net:
        aliases:
          - "choco"

  managerDb:
    image: postgres:15
    container_name: choco_database
    environment:
      POSTGRES_USER: dadyarri
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: choco
    volumes:
      - chocoPgData:/var/lib/postgresql/data
    ports:
      - "7232:5432"
    networks:
      - net


volumes:
  chocoPgData:
    
networks:
  net:
    driver: bridge
